from tkinter import *
from tkinter import ttk
top = Tk()
top.title("Welcome to Cloud Computing app")
tab_ctrl = ttk.Notebook(top)
tab1 = ttk.Frame(tab_ctrl)
tab2 = ttk.Frame(tab_ctrl)
tab_ctrl.add(tab1, text='First')
tab_ctrl.add(tab2, text='Second')
lb1=Label(tab1, text= 'l1', padx=5, pady=5)
lb1.grid(column=0, row=0)
lb2=Label(tab2, text= 'l2', padx=5, pady=5)
lb2.grid(column=0, row=0)
tab_ctrl.pack(expand=1, fill='both')
top.mainloop()
